### ISSUE TITLE
Latest 0.0.24 provider plugin bug when creating pingfederate_idp_adapter resources

### ISSUE THREAD

**Issue by ParadigmZero** [iwarapter/terraform-provider-pingfederate#206]
Terraform version ( tested on):
1.1.6, latest
PingFederate version: 9.3.3-edge
Provider version: 0.0.24 , latest as of posting

When making a simple pingfederate_idp_adapter (Resource):

```Stack trace from the terraform-provider-pingfederate_v0.0.24 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 133 [running]:
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.expandPluginConfiguration({0xc001001c00, 0x1, 0xc000496000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/expanders.go:249 +0x3c5
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.validateConfiguration(0xc000d45e70, 0xc001516760)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:142 +0x68
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.resourcePingFederateIdpAdapterResource.func1({0xea9078, 0xc0009b11c0}, 0xc000e008f0, {0xd70b00, 0xc000497000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/resource_pingfederate_idp_adapter.go:53 +0x31c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0002ce750, {0xea9078, 0xc0009b11c0}, 0xc000e008f0, 0xc000e14060, 0xdc2d40, {0xd70b00, 0xc000497000}, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/schema.go:543 +0x445
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xea9af8, {0xea9078, 0xc0009b11c0}, 0xc000e008f0, 0x0, {0xd70b00, 0xc000497000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:517 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000b2018, {0xea9078, 0xc0009b11c0}, 0xc0009acd20)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:703 +0x8fd
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000502b80, {0xea9120, 0xc0009cd950}, 0xc000ab6e70)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:578 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xd41d40, 0xc000502b80}, {0xea9120, 0xc0009cd950}, 0xc0000b9ec0, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007bee00, {0xeb6228, 0xc0007fcb60}, 0xc0009ae240, 0xc0007f6810, 0x1413488, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0007bee00, {0xeb6228, 0xc0007fcb60}, 0xc0009ae240, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:919 +0x294

Error: The terraform-provider-pingfederate_v0.0.24 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERROR: 1
```

Example resource to trigger error. Note, that the pingfederate_idp_adapter resources that trigger the errors do not have all the fields filled out (which are within the configuration block).

So, if you make this resource, you should be able to replicate the error:

```
resource "pingfederate_idp_adapter" "dummy" {
    name = "dummy"
    plugin_descriptor_ref {
    id = "com.pingidentity.adapters.htmlform.idp.HtmlFormIdpAuthnAdapter"
  }
  configuration {
  }
  attribute_contract {
      core_attributes {
      name      = "policy.action"
      masked    = false
      pseudonym = false
    }
  }
}
```
In the above example there are not `fields` in the configuration, block, however I believe just missing one of the `fields` will produce this crash.

In a more complex configuration, with what we believe all the required fields filled in etc. we get the following error also:

```Stack trace from the terraform-provider-pingfederate_v0.0.24 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9c427]

goroutine 1230 [running]:
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.hasField({0xc000fd0048, 0x11}, 0xc000081000)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:167 +0x27
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.validateConfiguration(0xc000bff8a8, 0xc000ab2040)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:145 +0xfc
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.resourcePingFederateIdpAdapterResource.func1({0xea9078, 0xc000be56c0}, 0xc000df35f0, {0xd70b00, 0xc000080c00})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/resource_pingfederate_idp_adapter.go:53 +0x31c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000750750, {0xea9078, 0xc000be56c0}, 0xc000df35f0, 0xc000e7c060, 0xdc2d40, {0xd70b00, 0xc000080c00}, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/schema.go:543 +0x445
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xea9af8, {0xea9078, 0xc000be56c0}, 0xc000df35f0, 0x0, {0xd70b00, 0xc000080c00})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:517 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00000c018, {0xea9078, 0xc000be56c0}, 0xc000ec9680)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:703 +0x8fd
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc00020e800, {0xea9120, 0xc000d0b440}, 0xc00061dab0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:578 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xd41d40, 0xc00020e800}, {0xea9120, 0xc000d0b440}, 0xc0000b8e40, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00074fc00, {0xeb6228, 0xc0008389c0}, 0xc000f6f8c0, 0xc000866810, 0x1413488, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00074fc00, {0xeb6228, 0xc0008389c0}, 0xc000f6f8c0, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:919 +0x294

Error: The terraform-provider-pingfederate_v0.0.24 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## Another way to repliate error ##

Replicate error:

```
resource "pingfederate_idp_adapter" "example" {
  name = "example"
  plugin_descriptor_ref {
    id = "com.pingidentity.adapters.httpbasic.idp.HttpBasicIdpAuthnAdapter"
  }

  configuration {
    tables {
      name = "Credential Validators"
      rows {
        fields {
          name  = "Password Credential Validator Instance"
          value = "foo"
        }
      }
    }
  }

  attribute_contract {
    core_attributes {
      name      = "username"
      pseudonym = true
    }
    extended_attributes {
      name = "sub"
    }
  }
}
```

Error output:

```Stack trace from the terraform-provider-pingfederate_v0.0.24 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9c427]

goroutine 82 [running]:
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.hasField({0xc000330420, 0x5}, 0xc000056800)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:167 +0x27
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.validateConfiguration(0xc000ac2200, 0xc001172480)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:145 +0xfc
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.resourcePingFederateIdpAdapterResource.func1({0xea9078, 0xc0000a54c0}, 0xc000945110, {0xd70b00, 0xc000057000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/resource_pingfederate_idp_adapter.go:53 +0x31c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0001ca750, {0xea9078, 0xc0000a54c0}, 0xc000945110, 0xc000d25650, 0xdc2d40, {0xd70b00, 0xc000057000}, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/schema.go:543 +0x445
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xea9af8, {0xea9078, 0xc0000a54c0}, 0xc000945110, 0x0, {0xd70b00, 0xc000057000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:517 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00000c030, {0xea9078, 0xc0000a54c0}, 0xc000c8a410)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:703 +0x8fd
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc00019ea80, {0xea9120, 0xc000c6fb90}, 0xc0011bbab0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:578 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xd41d40, 0xc00019ea80}, {0xea9120, 0xc000c6fb90}, 0xc000c4b620, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007eee00, {0xeb6228, 0xc0005904e0}, 0xc000bd2000, 0xc000824810, 0x1413488, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0007eee00, {0xeb6228, 0xc0005904e0}, 0xc000bd2000, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:919 +0x294

Error: The terraform-provider-pingfederate_v0.0.24 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
can be fixed. The output above should help diagnose the issue.

ERROR: 1
```

**Comment by ParadigmZero** [comment]
Here is another similar error:

**Comment by ParadigmZero** [comment]
```Stack trace from the terraform-provider-pingfederate_v0.0.24 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9c427]

goroutine 1040 [running]:
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.hasField({0xc000f1aed0, 0x11}, 0xc000056400)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:167 +0x27
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.validateConfiguration(0xc0009da208, 0xc000d056c0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/utils.go:145 +0xfc
github.com/iwarapter/terraform-provider-pingfederate/pingfederate.resourcePingFederateIdpAdapterResource.func1({0xea9078, 0xc000cf9ec0}, 0xc000b0d040, {0xd70b00, 0xc000529000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/pingfederate/resource_pingfederate_idp_adapter.go:53 +0x31c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00066a750, {0xea9078, 0xc000cf9ec0}, 0xc000b0d040, 0xc000a3bc50, 0xdc2d40, {0xd70b00, 0xc000529000}, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/schema.go:543 +0x445
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xea9af8, {0xea9078, 0xc000cf9ec0}, 0xc000b0d040, 0x0, {0xd70b00, 0xc000529000})
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:517 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00000c030, {0xea9078, 0xc000cf9ec0}, 0xc0008fcc30)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:703 +0x8fd
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0000d8980, {0xea9120, 0xc000882a20}, 0xc0008fe000)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:578 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xd41d40, 0xc0000d8980}, {0xea9120, 0xc000882a20}, 0xc000f0b1a0, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000354e00, {0xeb6228, 0xc0005f6b60}, 0xc00121a000, 0xc0006cc7e0, 0x1413488, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000354e00, {0xeb6228, 0xc0005f6b60}, 0xc00121a000, 0x0)
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-pingfederate/terraform-provider-pingfederate/vendor/google.golang.org/grpc/server.go:919 +0x294

Error: The terraform-provider-pingfederate_v0.0.24 plugin crashed!```

**Comment by ParadigmZero** [comment]
Here is another example of an error with a simple reproducer:
